export const COM_TYPES = {
  ActionBar: 'TiActionBar',
  Button: 'TiButton',
  Pager: 'TiPager',

  Sidebar: 'TiSidebar',
  Tabs: 'TiTabs',
  Input: 'TiInput',
  Check: 'TiCheck',
  Transfer: 'TiTransfer',
  Block: 'TiBlock',
  Cell: 'TiCell',
  Field: 'TiField',
  Form: 'TiForm',
  LayoutGrid: 'TiLayoutGrid',
  LayoutTabs: 'TiLayoutTabs',
  MainFrame: 'TiMainFrame',
  HtmlSnippet: 'TiHtmlSnippet',
  Icon: 'TiIcon',
  Label: 'TiLabel',
  Loading: 'TiLoading',
  Roadblock: 'TiRoadblock',
  Unknown: 'TiUnknown',
  List: 'TiList',
  Table: 'TiTable',
};
