export const COM_TYPES = {
  //------------------- ACTION
  ActionBar: 'TiActionBar',
  Button: 'TiButton',
  Pager: 'TiPager',
  Sidebar: 'TiSidebar',
  Tabs: 'TiTabs',
  //------------------- EDIT
  EditCode: 'TiEditCode',
  EditPair: 'TiEditPair',
  //------------------- TILE
  HtmlSnippet: 'TiHtmlSnippet',
  Icon: 'TiIcon',
  Label: 'TiLabel',
  Loading: 'TiLoading',
  Roadblock: 'TiRoadblock',
  Tags: 'TiTags',
  Thumb: 'TiThumb',
  Unknown: 'TiUnknown',

  //------------------- INPUT
  Check: 'TiCheck',
  Droplist: 'TiDroplist',
  Input: 'TiInput',
  InputCurrency: 'TiInputCurrency',
  InputDate: 'TiInputDate',
  InputDatetime: 'TiInputDatetime',
  InputTime: 'TiInputTime',
  InputColor: 'TiInputColor',
  InputIcon: 'TiInputIcon',
  InputGroup: 'TiInputGroup',
  InputNum: 'TiInputNum',
  InputText: 'TiInputText',
  Toggle: 'TiToggle',
  Transfer: 'TiTransfer',

  //------------------- SHELF
  Block: 'TiBlock',
  Cell: 'TiCell',
  Field: 'TiField',
  Form: 'TiForm',
  FormTab: 'TiFormTab',
  GridFields: 'TiGridFields',
  LayoutGrid: 'TiLayoutGrid',
  LayoutTabs: 'TiLayoutTabs',
  MainFrame: 'TiMainFrame',
  //------------------- VIEW
  Falls: 'TiFalls',
  List: 'TiList',
  Table: 'TiTable',
  Wall: 'TiWall',
};
