import { TabsProps } from '../ti-tabs-types';

export default {
  name: 'very-many',
  text: 'i18n:ti-tabs-example-very-many',
  comConf: {
    className: 'fit-parent',
    tabItemSpace: 'm',
    tabsAlign: 'left',
    tabsAt: 'top',
    value: 1,
    options: [
      { icon: 'zmdi-cast-connected', text: 'AAA' },
      { icon: 'zmdi-favorite', text: 'BBB' },
      { icon: 'zmdi-favorite', text: 'CCC' },
      { icon: 'zmdi-favorite', text: 'DDD' },
      { icon: 'zmdi-favorite', text: 'EEE' },
      { icon: 'zmdi-favorite', text: 'FFF' },
      { icon: 'zmdi-favorite', text: 'GGG' },
      { icon: 'zmdi-favorite', text: 'HHH' },
      { icon: 'zmdi-favorite', text: 'III' },
      { icon: 'zmdi-favorite', text: 'JJJ' },
      { icon: 'zmdi-favorite', text: 'KKK' },
      { icon: 'zmdi-favorite', text: 'LLL' },
      { icon: 'zmdi-favorite', text: 'MMM' },
      { icon: 'zmdi-favorite', text: 'NNN' },
      { icon: 'zmdi-favorite', text: 'OOO' },
      { icon: 'zmdi-favorite', text: 'PPP' },
      { icon: 'zmdi-favorite', text: 'QQQ' },
      { icon: 'zmdi-favorite', text: 'RRR' },
      { icon: 'zmdi-favorite', text: 'SSS' },
      { icon: 'zmdi-favorite', text: 'TTT' },
    ],
  } as TabsProps,
};
